/**
 * Core domain types.
 *
 * Vocabulary note: docs/SPEC.md specifies the `kind` column as `episode` or
 * `good`, and PRODUCT.md rule 3 defines an episode as one moment. The
 * prototype stores the string "hard" internally and carries a migrate() that
 * rewrites older shapes. That is a legacy artifact of the prototype's own
 * history, not a product decision. This is a fresh database with nothing to
 * migrate, so we use the vocabulary the spec and the product rules use.
 * Recorded in docs/DECISIONS.md.
 */

/** 1 to 4. See STAGES. Not a severity rating, a stage reached. */
export type Stage = 1 | 2 | 3 | 4;

export type EntryKind = 'episode' | 'good';

export interface Entry {
  id: string;
  /**
   * ISO 8601 local time. The moment it happened, not the moment it was
   * logged. Backdating must stay exact and always correctable.
   */
  at: string;
  kind: EntryKind;
  /** required for an episode, null for a good day */
  stage: Stage | null;
  /** single value drawn from the parent's own list */
  trigger: string | null;
  behaviors: string[];
  /** "Nothing we tried helped" is exclusive of every other value */
  tools: string[];
  /** minutes back to baseline. Required for an episode. */
  minutes: number | null;
  source: string;
  note: string | null;
  flagged: boolean;
  created_at: string;
  /** null until the first edit */
  updated_at: string | null;
}

export type ChangeKind = 'med' | 'therapy' | 'school' | 'other';

export interface Change {
  id: string;
  kind: ChangeKind;
  label: string;
  /** free text, e.g. "10mg twice daily". Medication only. */
  dose: string;
  /** ISO date */
  start: string;
  /**
   * ISO date or null.
   *
   * Records overlap. NEVER infer an end from the start of the next record.
   * The earlier model did exactly that and silently recorded Ritalin as
   * stopped on the day melatonin started, which is a false clinical statement
   * generated by a layout assumption. See PRODUCT.md rule 8.
   */
  end: string | null;
  note: string;
}

export interface Libraries {
  triggers: string[];
  behaviors: string[];
  tools: string[];
  sources: string[];
}

export interface Settings {
  onboarded: boolean;
  childName: string;
  childAge: string;
  contact: string;
  /** the four strengths. These lead the sitter page, before any trigger. */
  loves: string;
  proudOf: string;
  laughs: string;
  alwaysTrue: string;
  communication: string;
  pleaseDont: string;
  worthKnowing: string;
  theme: 'light' | 'dark' | 'auto';
  lib: Libraries;
}

/** The in-progress entry, written on a debounce. Losing work is unacceptable. */
export interface Draft {
  kind: EntryKind;
  at: string;
  stage: Stage | 0;
  trigger: string | null;
  behaviors: string[];
  tools: string[];
  minutes: number;
  source: string;
  note: string;
  flagged: boolean;
  /** set when editing an existing entry rather than creating one */
  editingId: string | null;
}

export const STAGES: ReadonlyArray<{ n: Stage; name: string; ds: string }> = [
  { n: 1, name: 'Caught it early', ds: 'Pulled out of it before it took hold' },
  { n: 2, name: 'Shut down', ds: 'Went quiet, withdrew, stopped talking' },
  { n: 3, name: 'Argued through it', ds: 'Defending, arguing, trying to regain control' },
  { n: 4, name: 'Full meltdown', ds: 'Lost it completely' },
];

export const CHANGE_KINDS: ReadonlyArray<{ k: ChangeKind; label: string; hint: string }> = [
  { k: 'med', label: 'Medication', hint: 'a drug, a dose, or stopping one' },
  { k: 'therapy', label: 'Therapy', hint: 'ABA, OT, speech, counselling' },
  { k: 'school', label: 'School', hint: 'new class, teacher, term, routine' },
  { k: 'other', label: 'Something else', hint: 'a strategy, a move, anything' },
];

export const NOTHING_HELPED = 'Nothing we tried helped';

/** The exclusive tool. Matches the prototype's /^nothing/i test. */
export function isNothingHelped(tool: string): boolean {
  return /^nothing/i.test(tool);
}

export function stageByNumber(n: Stage): { n: Stage; name: string; ds: string } {
  const found = STAGES.find((s) => s.n === n);
  if (!found) throw new Error(`Unknown stage: ${n}`);
  return found;
}

export function defaultLibraries(): Libraries {
  return {
    triggers: ['Loud noise', 'Transition', 'Told no', 'Crowded', 'Clothing', 'Hungry', 'Tired', 'Unknown'],
    behaviors: ['Crying', 'Screaming', 'Covering ears', 'Hitting', 'Withdrew', 'Bolted', 'Head-banging'],
    tools: [
      'Headphones',
      'Dark room',
      'Weighted blanket',
      'Deep pressure',
      'Ride in car',
      'Snack',
      NOTHING_HELPED,
    ],
    sources: ['Home', 'School', 'Sitter', 'Therapy', 'Out'],
  };
}

export function defaultSettings(): Settings {
  return {
    onboarded: false,
    childName: '',
    childAge: '',
    contact: '',
    loves: '',
    proudOf: '',
    laughs: '',
    alwaysTrue: '',
    communication: '',
    pleaseDont: '',
    worthKnowing: '',
    theme: 'auto',
    lib: defaultLibraries(),
  };
}
